project:
  type: book

book:
  title: "Statistical Rethinking (2nd ed. 2023)"
  author: "Peter Baumgartner"
  date: last-modified
  date-format: YYYY-MM-DD HH:mm
  favicon: "img/favicon.ico"

  chapters:
    - index.qmd
    - 01-golem-of-prague.qmd
    - 02-small-and-large-worlds.qmd
    - 03-sampling-the-imaginary.qmd
    - 04-geocentric-models.qmd
    - 90-glossary.qmd
    - 95-references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: true
    toc-depth: 5
    toc-expand: true
    code-fold: show
    code-tools: true
    code-overflow: scroll
    code-link: true
    df-print: default

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true

editor: visual

execute:
    echo: fenced
    freeze: auto

language:
   crossref-fig-title: "Picture"
