project:
  type: book

book:
  title: "Statistical Rethinking (2nd ed. 2023)"
  author: "Peter Baumgartner"
  date: last-modified
  date-format: YYYY-MM-DD HH:mm

  chapters:
    - index.qmd
    - 01-golem-of-prague.qmd
    - 02-small-and-large-worlds.qmd
    - 03a-sampling-the-imaginary.qmd
    - 03b-sampling-the-imaginary.qmd
    - 04a-geocentric-models.qmd
    - 04b-geocentric-models.qmd
    - 95a-references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: true
    toc-depth: 5
  pdf:
    documentclass: scrreprt

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
    code-line-numbers: false
    R.options:
      knitr.graphics.auto_pdf: true

editor: visual

execute:
    echo: fenced
    freeze: auto
