project:
  type: book

book:
  title: "Statistical Rethinking (2nd ed. 2023)"
  author: "Peter Baumgartner"
  date: "2023-06-05"
  chapters:
    - index.qmd
    - 01a-golem-of-prague.qmd
    - 02a-small-and-large-worlds.qmd
    - 95a-references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false
  pdf:
    documentclass: scrreprt

knitr:
  opts_chunk:
    collapse: true
    code-line-numbers: true
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true

editor: visual

